# -*- coding: utf-8 -*-
"""hello

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S9pzaTfrMmZocu0dVyW4aJf7OyvQmXGU
"""

print("Hello World!")