# -*- coding: utf-8 -*-
"""operators

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QB9i0wYj8dKmsZlpe0C_ueCnPPwn2MPA
"""

#Arithematic Operations in Python

sum = 2+2
print(sum)
diff = 2-2
print(diff)
divide = 2/2
print(divide)
mul = 2+2
print(mul)