# -*- coding: utf-8 -*-
"""rule_based_chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rE08pfFE9TLm9SzCtFY6nfmuhB2kdhCS
"""

# University Chatbot (Lab Task)

print("===== University Chatbot =====")
print("Type 'bye' to exit\n")

while True:
    user = input("Enter your question: ").lower()

    if user == "bye":
        print("Chatbot: Thank you! Goodbye.")
        break

    elif user == "hello" or user == "hi":
        print("Chatbot: Hello Student! How can I help you?")

    elif "course" in user:
        print("Chatbot: Courses include Programming, Data Structures, and Mathematics.")

    elif "teacher" in user:
        print("Chatbot: Please contact your course instructor for details.")

    elif "exam" in user:
        print("Chatbot: Exams are conducted at the end of each semester.")

    elif "time table" in user or "schedule" in user:
        print("Chatbot: Your timetable is available on the notice board.")

    elif "fee" in user:
        print("Chatbot: Please visit the accounts office for fee details.")

    elif "library" in user:
        print("Chatbot: Library is open from 9 AM to 5 PM.")

    else:
        print("Chatbot: Sorry, I do not understand your question.")